{
 "title": "ProxySQL Host Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(proxysql_uptime_seconds_total, instance)"
   },
   {
    "name": "endpoint",
    "query": "label_values(proxysql_connpool_conns, endpoint)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(proxysql_client_connections_connected{instance=~\"$instance\"},job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Connection, Command & Prepared Statement Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connection Pool Backend Status",
   "type": "stat",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxysql_connpool_conns_status{instance=~\"$instance\", endpoint=~\"$endpoint\"}",
     "legendFormat": "HG{{hostgroup}}: {{endpoint}}"
    }
   ]
  },
  {
   "title": "Connection Statistics (irate conn/s)",
   "type": "gauge",
   "description": "Total number of client & server connections (created|delayed|aborted).",
   "gridPos": { "h": 4, "w": 16, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(proxysql_client_connections_total{status=\"created\"}[$__rate_interval])",
     "legendFormat": "Client Created"
    },
    {
     "expr": " irate(proxysql_client_connections_total{status=\"aborted\"}[$__rate_interval])",
     "legendFormat": "Client Aborted"
    },
    {
     "expr": "irate(proxysql_server_connections_total{status=\"created\"}[$__rate_interval])",
     "legendFormat": "Server Created"
    },
    {
     "expr": "irate(proxysql_server_connections_total{status=\"aborted\"}[$__rate_interval])",
     "legendFormat": "Server Aborted"
    },
    {
     "expr": "irate(proxysql_server_connections_total{status=\"delayed\"}[$__rate_interval])",
     "legendFormat": "Server Delayed"
    }
   ]
  },
  {
   "title": "Error Counters (irate err/s)",
   "type": "stat",
   "gridPos": { "h": 15, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(proxysql_access_denied_wrong_password_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Wrong Password"
    },
    {
     "expr": "irate(proxysql_access_denied_max_user_connections_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Max Connections Reached"
    },
    {
     "expr": "irate(proxysql_access_denied_max_connections_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Max User Connections Reached"
    },
    {
     "expr": "irate(proxysql_max_connect_timeouts_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Backend Max Connect Timeout"
    },
    {
     "expr": "irate(proxysql_backend_lagging_during_query_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Queries failed on SHUNNED server"
    },
    {
     "expr": "irate(proxysql_backend_offline_during_query_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Queries failed on OFFLINE server"
    },
    {
     "expr": "irate(proxysql_mysql_unexpected_frontend_packets_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Unexpected Packet Received"
    }
   ]
  },
  {
   "title": "Frontend Usage (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxysql_client_connections_connected{instance=~\"$instance\",job=\"$job\"}/proxysql_mysql_max_connections{instance=~\"$instance\",job=\"$job\"}*100",
     "legendFormat": "Frontend Usage (%)"
    }
   ]
  },
  {
   "title": "Connection Overview",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxysql_client_connections_connected{instance=~\"$instance\",job=\"$job\"}",
     "legendFormat": "Frontend Connections"
    },
    {
     "expr": "sum(proxysql_connpool_conns{instance=~\"$instance\",job=\"$job\",status=\"used\"})",
     "legendFormat": "Backend Connections (in-use)"
    },
    {
     "expr": "sum(proxysql_connpool_conns{instance=~\"$instance\",job=\"$job\",status=\"free\"})",
     "legendFormat": "Backend Connections (free)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxysql_active_transactions{instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(proxysql_slow_queries_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Frontend Send Rate (irate byte/s)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(proxysql_queries_frontends_bytes_total{instance=~\"$instance\",job=\"$job\",traffic_flow=\"sent\"}[$__rate_interval])",
     "legendFormat": "Frontend Send Rate"
    }
   ]
  },
  {
   "title": "Frontend Receive Rate (irate byte/s)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(proxysql_queries_frontends_bytes_total{traffic_flow=\"received\",instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Frontend Receive Rate"
    }
   ]
  },
  {
   "title": "Backend Send Rate (irate byte/s)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(proxysql_queries_backends_bytes_total{traffic_flow=\"sent\",instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Backend Send Rate"
    }
   ]
  },
  {
   "title": "Backend Receive Rate (irate byte/s)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(proxysql_queries_backends_bytes_total{traffic_flow=\"received\",instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Backend Receive Rate"
    }
   ]
  },
  {
   "title": "Connection Pool Internals (irate op/s)",
   "type": "graph",
   "description": "- The number of requests made to the connection pool (get)\n- The number of connections returned to the connection pool (push)",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_myhgm_myconnpool_get_total{instance=~\"$instance\",job=\"$job\",purpose=\"ping\"}[$__rate_interval])",
     "legendFormat": "Ping Requested"
    },
    {
     "expr": "irate(proxysql_connpool_get_conn_failure_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "No Connection Available"
    },
    {
     "expr": "irate(proxysql_myhgm_myconnpool_push_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Connection Returned"
    },
    {
     "expr": "irate(proxysql_myhgm_myconnpool_reset_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Connection Reset"
    },
    {
     "expr": "irate(proxysql_myhgm_myconnpool_destroy_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Connection Destroyed"
    }
   ]
  },
  {
   "title": "Connection Pool Backend Latency (µs)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "proxysql_connpool_conns_latency_us{instance=~\"$instance\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{endpoint}} HG{{hostgroup}}"
    }
   ]
  },
  {
   "title": "Connection Pool Backend Routing (irate queries/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_connpool_conns_queries_total{instance=~\"$instance\",endpoint=~\"$endpoint\"}[$__rate_interval])",
     "legendFormat": "HG{{hostgroup}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Frontend Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxysql_client_connections_connected{instance=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "In-Use Backend Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxysql_connpool_conns{instance=~\"$instance\",endpoint=~\"$endpoint\",status=\"used\"}",
     "legendFormat": "{{endpoint}} HG{{hostgroup}}"
    }
   ]
  },
  {
   "title": "Available Backend Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxysql_connpool_conns{instance=~\"$instance\",endpoint=~\"$endpoint\",status=\"free\"}",
     "legendFormat": "{{endpoint}} HG{{hostgroup}}"
    }
   ]
  },
  {
   "title": "Connection Status - Ok (irate conn/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_connpool_conns_total{instance=~\"$instance\",endpoint=~\"$endpoint\",status=\"ok\"}[$__rate_interval])",
     "legendFormat": "HG{{hostgroup}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Connection Status  -  Error (irate conn/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_connpool_conns_total{instance=~\"$instance\",endpoint=~\"$endpoint\",status=\"err\"}[$__rate_interval])",
     "legendFormat": "{{endpoint}} HG{{hostgroup}} {{status}}"
    }
   ]
  },
  {
   "title": "Command Statistics (irate com/s)",
   "type": "graph",
   "description": "Total number of client & server connections (created|delayed|aborted).",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "c/s" } },
   "yaxes": [
    { "format": "c/s" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_com_autocommit_total[$__rate_interval])",
     "legendFormat": "com_autocommit"
    },
    {
     "expr": "irate(proxysql_com_autocommit_filtered_total[$__rate_interval])",
     "legendFormat": "com_autocommit_filtered"
    },
    {
     "expr": "irate(proxysql_com_rollback_total[$__rate_interval])",
     "legendFormat": "com_rollback"
    },
    {
     "expr": "irate(proxysql_com_rollback_total_filtered[$__rate_interval])",
     "legendFormat": "com_rollback_filtered"
    },
    {
     "expr": "irate(proxysql_com_backend_set_names_total[$__rate_interval])",
     "legendFormat": "com_backend_set_names"
    },
    {
     "expr": "irate(proxysql_com_backend_change_user_total[$__rate_interval])",
     "legendFormat": "com_backend_change_user"
    },
    {
     "expr": "irate(proxysql_com_backend_init_db_total[$__rate_interval])",
     "legendFormat": "com_backend_init_db"
    },
    {
     "expr": "irate(proxysql_com_commit_cnt_filtered_total[$__rate_interval])",
     "legendFormat": "com_commit_filtered"
    },
    {
     "expr": "irate(proxysql_com_frontend_set_names_total[$__rate_interval])",
     "legendFormat": "com_frontend_set_names"
    },
    {
     "expr": "irate(proxysql_com_frontend_use_db_total[$__rate_interval])",
     "legendFormat": "com_frontend_use_db"
    },
    {
     "expr": "irate(proxysql_com_frontend_use_db_total[$__rate_interval])",
     "legendFormat": "com_frontend_use_db"
    },
    {
     "expr": "irate(proxysql_com_commit_cnt_total[$__rate_interval])",
     "legendFormat": "com_commit"
    },
    {
     "expr": "irate(proxysql_com_commit_cnt_filtered_totalotal[$__rate_interval])",
     "legendFormat": "com_commit_filtered"
    },
    {
     "expr": "irate(proxysql_selects_for_update__autocommit0_total[$__rate_interval])",
     "legendFormat": "com_select_for_update_to_autocommit_off"
    }
   ]
  },
  {
   "title": "Connection Pool Backend Throughput SENT (irate MB/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_connpool_data_bytes_total{instance=~\"$instance\",endpoint=~\"$endpoint\",traffic_flow=\"sent\"}[$__rate_interval])/(1024*1024)",
     "legendFormat": "HG{{hostgroup}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Connection Pool Backend Throughput RECV (irate MB/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_connpool_data_bytes_total{instance=~\"$instance\",endpoint=~\"$endpoint\",traffic_flow=\"recv\"}[$__rate_interval])/(1024*1024)",
     "legendFormat": "HG{{hostgroup}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Connection Pool Frontend Throughput (irate b/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_queries_frontends_bytes_total{instance=~\"$instance\",traffic_flow=\"received\"}[$__rate_interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "irate(proxysql_queries_frontends_bytes_total{instance=~\"$instance\",traffic_flow=\"sent\"}[$__rate_interval])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Backend MySQL Errors",
   "type": "graph",
   "description": "Tracks the mysql errors encountered",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_error_total[$__rate_interval])",
     "legendFormat": "HG{{hostgroup}} {{address}}:{{port}}"
    }
   ]
  },
  {
   "title": "Frontend MySQL Errors",
   "type": "graph",
   "description": "Tracks the MySQL errors generated by ProxySQL",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_mysql_error_total[$__rate_interval]) OR on() vector(0)",
     "legendFormat": "HG{{hostgroup}}  {{address}}:{{port}}"
    }
   ]
  },
  {
   "title": "Frontend Prepared Statement Ops (irate op/s)",
   "type": "graph",
   "description": "Tracks the ProxySQL errors encountered",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_com_frontend_stmt_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Backend Prepared Statement Ops (irate op/s)",
   "type": "graph",
   "description": "Tracks the ProxySQL errors encountered",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_com_backend_stmt_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Hostgroup Locked Info (irate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_hostgroup_locked_set_cmds_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Set Command"
    },
    {
     "expr": "irate(proxysql_hostgroup_locked_queries_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "HG Locked Queries"
    }
   ]
  },
  {
   "title": "Killed Backend Connections & Queries (irate err/s)",
   "type": "graph",
   "description": "Tracks the ProxySQL errors encountered",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_mysql_killed_backend_connections_total[$__rate_interval]) OR on() vector(0)",
     "legendFormat": "Killed Connections"
    },
    {
     "expr": "irate(proxysql_mysql_killed_backend_queries_total[$__rate_interval]) OR on() vector(0)",
     "legendFormat": "Killed Queries"
    }
   ]
  },
  {
   "title": "Clustering Status and Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Sync Status",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pulled_mysql_query_rules_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Query Rules - {{status}}"
    },
    {
     "expr": "irate(pulled_mysql_servers_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "MySQL Servers - {{status}}"
    },
    {
     "expr": "irate(pulled_mysql_servers_runtime_checks_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Runtime MySQL Servers - {{status}}"
    },
    {
     "expr": "irate(pulled_mysql_servers_replication_hostgroups_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "MySQL Replication Hostgroups - {{status}}"
    },
    {
     "expr": "irate(pulled_mysql_servers_galera_hostgroups_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "MySQL Group Replication Hostgroups - {{status}}"
    },
    {
     "expr": "irate(pulled_mysql_servers_group_replication_hostgroups_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "MySQL Galera Replication Hostgroups - {{status}}"
    },
    {
     "expr": "irate(pulled_mysql_servers_aws_aurora_hostgroups_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "MySQL Aurora Replication Hostgroups - {{status}}"
    },
    {
     "expr": "irate(pulled_mysql_users_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "MySQL Users - {{status}}"
    },
    {
     "expr": "irate(pulled_proxysql_servers_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "ProxySQL Servers - {{status}}"
    }
   ]
  },
  {
   "title": "Cluster Epoch Sync Conflicts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sync_conflict_mysql_servers_share_epoch_total[$__rate_interval])",
     "legendFormat": "MySQL Servers"
    },
    {
     "expr": "irate(sync_conflict_mysql_query_rules_share_epoch_total[$__rate_interval])",
     "legendFormat": "Query Rules"
    },
    {
     "expr": "irate(sync_conflict_mysql_users_share_epoch_total[$__rate_interval])",
     "legendFormat": "MySQL Users"
    },
    {
     "expr": "irate(sync_conflict_proxysql_servers_share_epoch_total[$__rate_interval])",
     "legendFormat": "ProxySQL Servers"
    }
   ]
  },
  {
   "title": "Cluster Version One Sync Prevented",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sync_delayed_mysql_servers_version_one_total[$__rate_interval])",
     "legendFormat": "MySQL Servers"
    },
    {
     "expr": "irate(sync_delayed_mysql_query_rules_version_one_total[$__rate_interval])",
     "legendFormat": "Query Rules"
    },
    {
     "expr": "irate(sync_delayed_mysql_users_version_one_total[$__rate_interval])",
     "legendFormat": "MySQL Users"
    },
    {
     "expr": "irate(sync_delayed_proxysql_servers_version_one_total[$__rate_interval])",
     "legendFormat": "ProxySQL Servers"
    }
   ]
  },
  {
   "title": "Backend Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Monitoring Check Status Totals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_mysql_monitor_connect_check_total{status=\"ok\"}[$__rate_interval])",
     "legendFormat": "Connect Ok"
    },
    {
     "expr": "irate(proxysql_mysql_monitor_connect_check_total{status=\"err\"}[$__rate_interval])",
     "legendFormat": "Connect Errors"
    },
    {
     "expr": "irate(proxysql_mysql_monitor_ping_check_total{status=\"ok\"}[$__rate_interval])",
     "legendFormat": "Ping Ok"
    },
    {
     "expr": "irate(proxysql_mysql_monitor_ping_check_total{status=\"err\"}[$__rate_interval])",
     "legendFormat": "Ping Errors"
    },
    {
     "expr": "irate(proxysql_mysql_monitor_read_only_check_total{status=\"ok\"}[$__rate_interval])",
     "legendFormat": "Read-Only Ok"
    },
    {
     "expr": "irate(proxysql_mysql_monitor_ping_check_total{status=\"err\"}[$__rate_interval])",
     "legendFormat": "Read-Only Errors"
    },
    {
     "expr": "irate(proxysql_mysql_monitor_replication_lag_check_total{status=\"ok\"}[$__rate_interval])",
     "legendFormat": "Replication Lag Ok"
    },
    {
     "expr": "irate(proxysql_mysql_monitor_replication_lag_check_total{status=\"err\"}[$__rate_interval])",
     "legendFormat": "Replication Lag Errors"
    }
   ]
  },
  {
   "title": "Query Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Cache Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_query_cache_count_get_total{status!='ok'}[$__rate_interval])",
     "legendFormat": "Total Gets"
    },
    {
     "expr": "irate(proxysql_query_cache_count_get_total{status='ok'}[$__rate_interval])",
     "legendFormat": "Get OK"
    },
    {
     "expr": "irate(proxysql_query_cache_count_set_total[$__rate_interval])",
     "legendFormat": "Total Sets"
    }
   ]
  },
  {
   "title": "Query Cache Growth Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_query_cache_bytes_total{op=\"read\"}[$__rate_interval])",
     "legendFormat": "Cache Read"
    },
    {
     "expr": "irate(proxysql_query_cache_bytes_total{op=\"written\"}[$__rate_interval])",
     "legendFormat": "Cache Written"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 195 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Allocation Statistics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "proxysql_jemalloc_allocated_bytes_total",
     "legendFormat": "jemalloc_allocated_bytes"
    }
   ]
  }
 ]
}