{
 "title": "Vault Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Vault Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vault_core_active" }
   ]
  },
  {
   "title": "Task count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecs_tasks" }
   ]
  },
  {
   "title": "PORT STATUS IP LB",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "port_status" }
   ]
  },
  {
   "title": "TG - Healthy Host Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "HealthyHostCount{TargetGroup=~\".*vault.*\", quantile=\"1\", AvailabilityZone=~\"us-east-1a\"}",
     "legendFormat": "{{TargetGroup}}"
    }
   ]
  },
  {
   "title": "TG - UnHealthy Host Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "UnHealthyHostCount{TargetGroup=~\".*vault.*\", quantile=\"1\", AvailabilityZone=~\"us-east-1a\"}",
     "legendFormat": "{{TargetGroup}}"
    }
   ]
  },
  {
   "title": "Audit Log Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "vault_audit_log_request{quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "LB - Healthy Host Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "HealthyHostCount{LoadBalancer=~\".*vault.*\", quantile=\"1\"}",
     "legendFormat": "{{LoadBalancer}}"
    }
   ]
  },
  {
   "title": "LB - UnHealthy Host Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "UnHealthyHostCount{LoadBalancer=~\".*vault.*\", quantile=\"1\"}",
     "legendFormat": "{{LoadBalancer}}"
    }
   ]
  },
  {
   "title": "ECS - CPU Utilization ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "CPUUtilization{exported_job=\"AWS/ECS\", quantile=\"1\"} / 1000",
     "legendFormat": "{{ClusterName}}"
    }
   ]
  },
  {
   "title": "ECS - Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "MemoryUtilization{exported_job=\"AWS/ECS\", ClusterName=~\".*vault.*\", quantile=\"1\"}",
     "legendFormat": "{{ClusterName}}"
    }
   ]
  },
  {
   "title": "vault_barrier_get",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "targets": [
    { "expr": "vault_barrier_get" }
   ]
  },
  {
   "title": "vault_barrier_list",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "targets": [
    { "expr": "vault_barrier_list" }
   ]
  },
  {
   "title": "vault_barrier_list",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "targets": [
    { "expr": "vault_barrier_list" }
   ]
  },
  { "title": "Vault Cloudwatch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } }
 ]
}