{
 "title": "Services Memory/CPU Usage",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "resolution", "query": "1m, 2m, 3m, 5m" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "POD Count (Namespace)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"}) by(namespace, pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Pod Restart",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Micro Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", pod!~\"spot-ocean-metric-exporter.*\", pod!~\"domain-exporter.*\", pod!~\"elasticsearch.*\"}[$__rate_interval])) by (container) / sum(kube_pod_container_resource_requests{unit=\"core\", pod!~\"spot-ocean-metric-exporter.*\", pod!~\"domain-exporter.*\", pod!~\"elasticsearch.*\"}) by (container)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", pod!~\"spot-ocean-metric-exporter.*\", pod!~\"domain-exporter.*\", pod!~\"elasticsearch.*\"}[$__rate_interval])) by (container) / sum(kube_pod_container_resource_limits{ unit=\"core\", pod!~\"spot-ocean-metric-exporter.*\", pod!~\"domain-exporter.*\", pod!~\"elasticsearch.*\"}) by (container)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", pod!~\"spot-ocean-metric-exporter.*\", pod!~\"domain-exporter.*\", pod!~\"elasticsearch.*\"}) by (container) / sum(kube_pod_container_resource_requests{unit=\"byte\", pod!~\"spot-ocean-metric-exporter.*\", pod!~\"domain-exporter.*\", pod!~\"elasticsearch.*\"}) by (container)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", pod!~\"spot-ocean-metric-exporter.*\", pod!~\"domain-exporter.*\", pod!~\"elasticsearch.*\"}) by (container) / sum(kube_pod_container_resource_limits{unit=\"byte\", pod!~\"spot-ocean-metric-exporter.*\", pod!~\"domain-exporter.*\", pod!~\"elasticsearch.*\"}) by (container)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 8 },
   "targets": [
    { "expr": "probe_success" },
    { "expr": "probe_http_ssl > 0" },
    {
     "expr": "(probe_ssl_earliest_cert_expiry - time()) / 3600 / 24"
    },
    { "expr": "probe_http_status_code " },
    {
     "expr": "avg_over_time(probe_duration_seconds[1m])"
    },
    { "expr": "probe_tls_version_info" },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds[1m])"
    }
   ]
  },
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}